"""Furniture can see the render context (#74, lane A4 of epic #77).

`BEFORE_BODY` was a tuple of module-level constant strings, so a swatch could *paint*
`var(--accent)` but the page could never *print* the project's actual hex. Both frozen targets
print real values, and that limitation is what forced `design-system` into "show, never state".

An entry may now be a CALLABLE taking the per-render scratchpad. Plain strings are untouched,
which is the whole safety case: a template that does not opt in cannot change.

The issue called this "the change in this epic most likely to surprise" and asked for per-style
SHA oracles captured BEFORE the change rather than an assertion afterwards. They were, on the
committed cross-style fixture, and they are pinned below.
"""
import hashlib
import sys
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(SCRIPTS))

import render  # noqa: E402
from render import templates as render_templates  # noqa: E402

FIXTURE = (SCRIPTS / "tests" / "fixtures" / "crossstyle.md").read_text(encoding="utf-8")

# Captured on `main` at 1a25512, BEFORE this issue's change, by rendering the committed
# cross-style fixture through every style. Not recomputed afterwards — that would prove nothing.
#
# #61 RE-PINNED NINE OF THE TEN AT ONCE, which is unusual enough to justify here rather than
# nine times below. The fix is one line in `_steprail` — the `<details name>` group became the
# document instead of the fence — and the cross-style fixture carries a `steprail` fence, which
# every RICH style renders (with an "not accepted" warning where the type does not accept it).
# So every rich style's bytes move for one engine change. That is the case `crossstyle.sh`'s
# `--foundation` mode exists for, and it was run in that mode: nine moved, `plain` did not.
#
# **`plain` is untouched and that was MEASURED, not argued**: `plain` leaves a typed fence as a
# code listing and never renders a rail at all, so an engine change to the rail cannot reach it.
# `test_single_current_step.py::TestPlainStaysFrozen` pins exactly that, so the next person does
# not have to re-derive it.
#
# #24 RE-PINNED ALL THIRTEEN, INCLUDING `plain` (2026-08-03). Read this before assuming the
# paragraph above still holds — it no longer does, and saying so is the point.
#
# The footer and eyebrow are page FURNITURE: emitted by the shared frame for every style, `plain`
# included. #24 renamed them (`generated by hooks/render_artifact.py` -> `generated by
# design-doc-publish`, `rawgentic design artifact` -> `design artifact`, because rawgentic#807
# deleted the path both named) and added `<meta name="generator" content="design-doc-publish">`
# so `deploy_check.py` recognises engine output by markup instead of display prose. Every page
# this engine renders therefore moves by exactly +37 bytes. There is no way to change a false
# statement stamped on every page without moving every page.
#
# `crossstyle.sh` CANNOT express this: it hard-fails any `plain` movement in every mode
# (crossstyle.sh:140), `--foundation` included, whose docs say "`plain` still may not". So
# "which styles moved" is the wrong question here — all of them, by construction.
#
# What was verified instead, and it is strictly stronger: each style was rendered at the branch
# base and at HEAD, the three approved substitutions were applied to the BASE output, and the
# result was required to equal HEAD byte-for-byte. All 13 passed with zero unexpected
# differences, so these new pins record exactly the intended edit and cannot be blessing an
# unrelated regression. The stylesheet pin (`_STYLE` sha) did not move at all, which is the
# independent corroboration that no CSS drifted in with it.
#
# So: #73 is no longer the only sanctioned `plain` re-baseline. #24 is the second, for the one
# reason that can justify it — the frozen style's frame was telling every reader something untrue.
# #171 MOVED ALL TWELVE NON-PLAIN STYLES, and `plain` is untouched — which is the containment
# this oracle exists to prove. The legend's `dt` rules live in the SHARED block stylesheet, so
# one edit reaches every style that receives that layer; `plain` receives no block layer at all
# and its pin below came back EQUAL, exactly as it did for #133 and #134.
#
# The moved bytes were READ, not trusted. A unified diff of each committed page against a fresh
# render totals 204 lines ADDED, 0 removed and 0 changed — 17 lines per style across 12 styles,
# which is exactly the size of the added CSS block. Nothing else drifted in with it.
#
# What moved and why: `.blk-legend dt` coloured three tokens (`is-done`, `is-blocked`,
# `is-solid`) and ten others fell through to the neutral bar. A legend whose keys were
# `crit`/`warn`/`ok`/`note` — the four a roadmap actually uses — therefore rendered four
# identical grey bars, so the device that exists to say what a colour MEANS could not.
# Measured on the live `rawgentic-plan-graph` page before the fix.
# #173 MOVED ALL TWELVE NON-PLAIN STYLES, `plain` untouched, and the proof is unusually tight:
# every changed line, with `title="..."` stripped back out, is byte-identical to the line it
# replaced. 12 added, 12 removed, zero lines differing by anything else. A chip gained a hover
# tooltip and nothing else moved.
#
# `plain` renders a typed fence as a code listing and never invokes the block engine, so its pin
# came back EQUAL — the same containment signal #133, #134 and #171 each relied on.
PRE_74 = {
    # #148 RE-PINNED ALL THIRTEEN (2026-08-05), and the reason is the FIXTURE, not the engine.
    #
    # The cross-style fixture was missing FOUR of the seventeen block tags — `phases`, `flow`,
    # `composition` and `faq` — so a snapshot whose whole purpose is exercising the component
    # vocabulary never rendered four of its components. Two of them are FIRST-READ devices, which
    # made it worse than incomplete: `roadmap.html` and `workflow.html` lacked the very device
    # their own style opens with, so both would have failed #130's gate had anyone published them.
    # Adding the four fences moves every page, `plain` included, because every style renders the
    # fixture.
    #
    # CONTAINMENT, MEASURED, and the measurement caught a bad probe first. The claim is that the
    # engine is inert and every moved byte is the fixture's. Proven by rendering the OLD fixture
    # through the CURRENT engine and requiring every pin below to reproduce exactly: all 13 did.
    # So nothing here blesses a rendering change.
    #
    # The first attempt at that proof reported all 13 drifted, `plain` included, and it was the
    # PROBE that was wrong — it used `regen_rendered_styles.py`'s recipe (real title, pinned stamp,
    # doc id) while `_sha` below renders with `title="T"`, `generated_at="x"` and no doc id. Two
    # recipes exist in this tree for different jobs. Re-pinning from that probe would have written
    # garbage into the oracle while every test went green, which is exactly the failure mode this
    # file exists to prevent — recorded so the next person checks which recipe they are holding.
    #
    # Deltas are consistent with the edit: ~3.9 KB on each rich style, ~1.0 KB on `plain`, which
    # leaves a typed fence as a code listing instead of rendering a component.
    #
    # #134 moved EVERY non-plain style, and this time the MARKUP moved too: `_options` now emits a
    # real `.blk-lbl` label element per column, and the CSS-generated labels it replaces
    # (`content:"+ "`/`"- "` in the shared layer, `content:"FOR"`/`"AGAINST"` in `design`) are gone.
    # The cross-style fixture carries an `options` fence, and every rich style renders that fence —
    # `design` because it accepts the tag, the rest with a "not accepted … rendering it anyway"
    # warning — so one renderer change reaches twelve styles. `plain` leaves a typed fence as a code
    # listing and never invokes the block engine, so its pin below is UNTOUCHED and its recomputed
    # sha came back EQUAL to the value already here. That is the containment, measured.
    #
    # Verified the way this file's header prescribes, not by trusting the new numbers: all 13 styles
    # rendered at `origin/main` AND at HEAD, this change's three substitutions applied to the BASE
    # output, and the result required to equal HEAD byte-for-byte. 12 moved, 1 unmoved, ZERO
    # unexplained differences. The substitutions were DERIVED from the two trees (the stylesheet is
    # embedded verbatim in each page) rather than hand-typed, so a typo could not fake the pass.
    #
    # #133 moved EVERY non-plain style by exactly one declaration: `BLOCK_CSS` gained
    # `:root{--accent-soft:…}`, and `design` additionally swapped its inline accent mix for the
    # token. `plain` receives no block layer, so its pin below is UNTOUCHED — which is the
    # containment this oracle exists to prove, and #133's AC4 verbatim.
    #
    # Re-pinned, not re-derived, and verified the way this file's header describes rather than by
    # trusting the new numbers: each of the 13 styles was rendered at `origin/main` AND at HEAD,
    # the two approved substitutions were applied to the BASE output, and the result was required
    # to equal HEAD byte-for-byte. All 13 passed with ZERO unexplained differences, so these pins
    # record exactly the intended edit and cannot be blessing an unrelated regression.
    # Dark-link fix (owner report 2026-08-22): `_COMPONENT_STYLE` gained exactly one
    # declaration, `a{color:var(--accent)}` — links were browser-default dark blue on the
    # dark ground. Re-pinned per this file's discipline: all 13 styles rendered at
    # origin/main AND at HEAD, the single substitution applied to the BASE output, and the
    # result required to equal HEAD byte-for-byte. 12 moved with zero unexplained
    # differences; `plain` receives no component layer, and its recomputed sha came back
    # EQUAL to the pin below — untouched, which is the containment this oracle proves.
    "plain": "5c922fd3a4f8816efbe79fe4be4ff50a54b0538722d6a587222cf1be8a5310ea",
    # #76 moved `analysis` on purpose — the first of the seven frozen-target rebuilds.
    # Re-pinned with the reason beside it, as #68 did for `roadmap` and #75 for `uat`
    # (D57/D61). `plain` has not moved; `crossstyle.sh` is what proves containment.
    # #90 moved `analysis` — the SIBLING of the defect that issue names. Its
    # `confidence_chip` read a fenced "measured" as the author's own confidence, on the one
    # doc type whose purpose is separating confirmed from inferred. The fix lands at the
    # shared `render_sections` call site, so it reaches this resolver by the same line;
    # `templates/analysis.py` has documented this defect and asked for exactly that since #76.
    "analysis": "4d5d91b9d73235af9ccb8998b02739c41cc4782cc1556e17ebf26ae9b9789f8b",
    # #68 moved roadmap on purpose — TWICE, once per PR of the child, and each move is the
    # deliberate rebuild the issue asks for. PR 1 added the `composition` block and its CSS;
    # PR 2 added the `phases` band that contains it. Re-pinned rather than re-derived: this
    # pin proves #74 was inert, and a style that a LATER issue deliberately rebuilds has to be
    # re-pinned or the oracle only records that the repo once looked different. `plain` is the
    # frozen one; it has not moved and its own pin is untouched. The per-PR "only MY style
    # moved" guard is `crossstyle.sh`, and it is what proves this move was contained.
    # #90 moved it again: chips now read the section's PROSE, never a typed block's cells,
    # so a `## Risks` card carrying a findings row stops publishing DONE. This style is the
    # one the defect was measured on.
    # #166 moved it a third time, and ONLY it: the phase rail gained the status half of its
    # state vocabulary (`done`/`shipped`/`merged`, `active`/`wip`/`pending`, `blocked`/`failed`)
    # on the chip, the badge, the bar segment and the phase border. `done` was reaching a live
    # page as a GREY chip because no rule matched `.is-done`, which is the defect.
    #
    # CONTAINMENT, MEASURED, and it is the strongest form this oracle accepts: all 13 pins were
    # recomputed at HEAD and exactly ONE moved — this one. The other 12 came back EQUAL to the
    # values already here, `plain` included, so no shared layer drifted in alongside.
    #
    # The moved bytes were then read rather than trusted. A unified diff of the committed
    # `docs/rendered-styles/roadmap.html` against a fresh render reports 44 lines ADDED, 0
    # removed and 0 changed, and every added line is one of the new CSS rules. The three
    # severity rules this issue was told not to touch (`is-crit`, `is-warn`, `is-ok`) are
    # byte-for-byte what shipped — which is what lets every roadmap already published keep its
    # exact appearance. An additive stylesheet cannot repaint an existing page; that is why the
    # fix was built this way rather than by renaming the severity tokens.
    # Re-pinned: `.blk-ph-badge` moved from `flex:none` to `flex:0 1 auto;min-width:0` so a long
    # phase-rail meta line WRAPS inside its flex row instead of overflowing the page horizontally.
    # Also adds max-width:100%;white-space:normal;overflow-wrap:anywhere so a long unbreakable token
    # (a 64-char hash, a slash-joined issue run) breaks rather than pushing the badge wide
    # (a full-page 2381px scroll on a 780px viewport, owner-reported). Only the roadmap template
    # carries `blk-ph-badge`, so no other style moves; `crossstyle.sh` is the "only mine moved" guard.
    "roadmap": "45aa43a4c7534691dcdc3bd715ad011d72ef6b7eda4b29452fbd3694578ef3eb",
    # #76 rebuild — re-pinned; see the header note above.
    "report": "7cde215e701d7921fc5f037a0fde1333025f4a1e8b240ac7c24e0c3e1d582cd7",
    "design": "825b0358604eb8230a6d9d63922e86a948c3a42271fc1aa2c97178e9e4eb531e",
    # #90 moved it: `dashboard` shares `roadmap_status_chip`, so the same fix reaches it.
    # That sharing is why this could not be folded into #68 — see the issue's own note.
    "dashboard": "c860f50a35361782ef7e08b37b82cdad1f88def27768aafd6c37724daeb69581",
    "review": "5a95a41f0a41d17c08449a062f6278fb95cec89df25551315286124ca3ded792",
    "spec": "a92fdec42603510d262c4fcec57542799161d897aa65f531f2eedd7166ea2e4d",
    # #75 moved `uat` on purpose — the frozen-target rebuild. Re-pinned with the reason
    # beside it, the same treatment #68 gave `roadmap` (D57/D61). `plain` has not moved and
    # its own pin is untouched; the per-PR "only my style moved" guard is `crossstyle.sh`.
    "uat": "81a7e13ccedc10a2f91d977b0f4adb9df936e32d83ecda24c2a9a6d920b34080",
    "workflow": "f89175e9061d92ece0afa4d4ff93f1092c06bf5079df5b4264fae3c2823cfac3",
    # #42 adds this style, so its pin is CAPTURED here rather than inherited — there is no
    # "before" for a style that did not exist. What the oracle guards from now on is that
    # nothing else moves it.
    "design-system": "d3efa262cdeaa15597e49724f5b82444ab22674e2730a7eb2028ca325cd92ff8",
    "module-map": "f60156143d6f4bb881b8361dec3ee59f42f642291511d420845826ac8a251c18",
    "slide-deck": "c1205f74a1c31d4395ab01af14d05dd4b180cc5914e9404aee561c973d4f96ea",
    # #59 adds this style, so its pin is CAPTURED here rather than inherited — there is no
    # "before" for a style that did not exist, the same treatment #42 gave `design-system`.
    # What the oracle guards from now on is that nothing else moves it.
    #
    # CONTAINMENT, MEASURED rather than asserted: every one of the thirteen pins above was
    # recomputed at this commit and ALL THIRTEEN came back EQUAL, `plain` included. So adding
    # a style to the registry moved no other style's bytes, which is the invariant this file
    # exists to prove and the reason a new style may be pinned at introduction.
    #
    # Captured with THIS file's own `_sha` recipe (title="T", generated_at="x", no doc id),
    # not with `regen_rendered_styles.py`'s. Two recipes live in this tree for different jobs
    # and the header above records what happens when the wrong one is used.
    "minutes": "e70d7455762f9bc14621c70b782055ca719815d3d9965821fcef5422c0e26ce5",
}

PACK = {"accent": {"light": "#1e5f7a", "dark": "#7fd4f0"}}


def _sha(style, **kw):
    out = render.render_artifact(FIXTURE, title="T", style=style, generated_at="x", **kw)
    return hashlib.sha256(out.encode()).hexdigest()


class TestNothingThatDoesNotOptInMoves:
    """AC2 and AC3 — the risk the issue exists to contain."""

    def test_every_style_is_byte_identical_to_its_pre_change_sha(self):
        for style, sha in PRE_74.items():
            assert _sha(style) == sha, f"{style} moved; no template opted in, so nothing should"

    def test_the_oracle_covers_every_style_in_the_registry(self):
        """A pin that silently stops covering a style is not a pin."""
        assert set(PRE_74) == {"plain"} | set(render_templates.TEMPLATES)


class TestFurnitureCanReadThePack:
    """AC1."""

    def test_a_callable_entry_receives_the_context_and_its_output_reaches_the_page(self):
        seen = {}

        def probe(ctx):
            seen["pack"] = render.furniture_pack(ctx)
            return "<!--probe-->"

        original = render._templates.BEFORE_BODY["design"]
        render._templates.BEFORE_BODY["design"] = (probe,)
        try:
            # `_bind` captured the tuple at import, so rebuild this style's renderer.
            renderer, css, dec = render._TEMPLATES["design"]
            render._TEMPLATES["design"] = (render._bind("design"), css, dec)
            page = render.render_artifact(FIXTURE, title="T", style="design",
                                          generated_at="x", vdl=PACK)
        finally:
            render._templates.BEFORE_BODY["design"] = original
            renderer, css, dec = render._TEMPLATES["design"]
            render._TEMPLATES["design"] = (render._bind("design"), css, dec)

        assert seen["pack"] == PACK, "furniture could not see the render's VDL pack"
        assert "<!--probe-->" in page

    def test_furniture_pack_is_none_when_no_pack_was_resolved(self):
        assert render.furniture_pack({}) is None
        assert render.furniture_pack(None) is None

    def test_furniture_pack_refuses_a_non_dict(self):
        """A malformed pack must read as absent, not as something a callable indexes into."""
        assert render.furniture_pack({"_vdl_pack": "#ff0000"}) is None


class TestTheTrustBoundaryIsUnchanged:
    def test_the_scratchpad_carries_no_author_text_for_furniture_to_emit(self):
        """AC4. Furniture is emitted UNESCAPED because it is a trusted constant. A callable
        keeps that property only while what it can reach is repository config — so assert the
        pack the accessor hands back is the one the CALLER passed, never anything the document
        put there."""
        md = "# T\n\n```callout\nnote | <script>alert(1)</script>\n```\n"
        page = render.render_artifact(md, title="T", style="design", generated_at="x", vdl=PACK)
        assert "<script>alert(1)</script>" not in page
        assert "&lt;script&gt;" in page
