"""#16 wave 1: the seven constructs the renderer silently emitted as raw markdown.

Two hard rules this file exists to enforce:

* AC2 — `plain` stays BYTE-IDENTICAL. The new transforms are gated behind the
  `inline_fn` seam and a block-level `rich` switch; `plain` keeps today's `_inline`
  and today's block loop. Every richer style gets the fix.
* AC3 — escape-first. New transforms run on ALREADY-ESCAPED text and can never
  introduce an unescaped `<`.

The parser also MOVES to `render/markdown.py`, and the two def-time
`inline_fn=_inline` defaults become call-time lookups — without that, a fixed
`_inline` never reaches direct callers and the whole fix is inert.
"""
import re
import sys
from pathlib import Path

import pytest

SCRIPTS = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(SCRIPTS))

import render  # noqa: E402
from render import markdown as md  # noqa: E402


# --- the move, and the trap the empty module's docstring names -------------------

def test_parser_lives_in_markdown_module():
    """The parser moved out of __init__ into render/markdown.py."""
    for name in ("_inline", "_render_body_plain", "_render_roadmap",
                 "_is_table_separator", "_split_table_row"):
        assert hasattr(md, name), f"render.markdown must own {name}"


def test_inline_fn_is_a_call_time_lookup_not_a_def_time_default():
    """THE trap. A def-time default binds the ORIGINAL `_inline`, so replacing it
    would never reach a direct caller and the parser fix would be silently inert.

    Both renderers must resolve `_inline` at CALL time. Proven by swapping the
    module attribute and checking the swap is observed.
    """
    original = md._inline
    try:
        md._inline = lambda esc: "SWAPPED"
        assert "SWAPPED" in md._render_body_plain("hello"), (
            "_render_body_plain captured _inline at definition time"
        )
        assert "SWAPPED" in md._render_roadmap("## Heading\n\nhello"), (
            "_render_roadmap captured _inline at definition time"
        )
    finally:
        md._inline = original


# --- AC2: plain is byte-identical ------------------------------------------------

PROBE = """# Doc Title

Intro with a [link](https://example.com), *italic*, _under_ and **bold**.

1. first
2. second
3. third

- parent
  - nested child
- sibling

![alt text](https://example.com/i.png)

---

Done.
"""


def test_plain_output_is_unchanged_for_every_construct():
    """AC2: plain must still emit the raw markdown it always did — no <ol>, no <a>,
    no <em>, no <img>, no <hr>. This is the byte-identity contract, asserted as
    behaviour so a well-meaning 'fix' to plain fails here."""
    out = render._render_body(PROBE, style="plain")
    for tag in ("<ol>", "<a ", "<em>", "<img", "<hr"):
        assert tag not in out, f"plain must not gain {tag} (AC2 byte-identity)"
    assert "[link](https://example.com)" in out, "plain still shows the literal link"


def test_plain_matches_a_frozen_snapshot():
    """AC2 the blunt way: plain's bytes for the probe are FROZEN.

    The fixture was generated by rendering PROBE with the engine at `origin/main`
    BEFORE this change, and a differential run over five documents (probe, tables,
    fenced code, soft-wrap, hostile input) confirmed old == new for `plain` in every
    one. This pin is what keeps that true — any future edit that changes plain's
    output fails here with a byte diff.
    """
    frozen = (Path(__file__).parent / "fixtures" / "plain_probe_frozen.html").read_text()
    assert render._render_body(PROBE, style="plain") == frozen, (
        "plain output changed — AC2 forbids it; the new constructs belong behind "
        "the inline_fn seam and rich=True"
    )


def test_plain_still_corrupts_ordered_lists_on_purpose():
    """Uncomfortable but correct: AC2 pins plain, so plain KEEPS the run-on
    paragraph. The fix lands for every richer template. Asserting it explicitly
    stops someone 'helpfully' fixing plain and silently breaking byte-identity."""
    out = render._render_body(PROBE, style="plain")
    assert "1. first" in out and "<ol>" not in out


# --- AC1: the rich path renders every construct ----------------------------------

@pytest.fixture
def rich():
    return render._render_body(PROBE, style="design")


def test_ordered_list_renders(rich):
    assert "<ol>" in rich and "</ol>" in rich
    assert rich.count("<li>") >= 3
    assert "1. first" not in rich, "the marker must be consumed, not printed"


def test_link_renders(rich):
    assert '<a href="https://example.com"' in rich
    assert ">link</a>" in rich
    assert "[link](https://example.com)" not in rich


def test_italic_renders_both_markers(rich):
    assert "<em>italic</em>" in rich
    assert "<em>under</em>" in rich
    assert "*italic*" not in rich and "_under_" not in rich


def test_bold_still_renders_and_is_not_eaten_by_italic(rich):
    assert "<strong>bold</strong>" in rich
    assert "<em></em>" not in rich, "** must not be parsed as two italics"


def test_an_off_host_image_is_refused_and_stays_literal(rich):
    """#23 flipped this test. It used to assert `src="https://example.com/i.png"` — i.e. it
    PINNED an active cross-host fetch. `test_frame_ownership.py`'s
    `test_no_style_reaches_an_external_host` has a NAME that implies the opposite guarantee,
    but its fixture holds no image, so it never actually exercised one: the suite's real
    problem was missing stimulus, not two assertions colliding. The guarantee wins anyway,
    because a page that fetches another host also fails the pre-publish lint gate and so can
    never be published.

    `![alt text](https://example.com/i.png)` is PROBE's image, and PROBE is also the frozen
    input for plain's byte-identity snapshot — so the URL stays as it is and the assertion
    moves instead.
    """
    assert "<img" not in rich
    assert "![alt text](https://example.com/i.png)" in rich
    # and it must not be quietly re-consumed by the link pass into `!<a href=…>`
    assert 'href="https://example.com/i.png"' not in rich


def test_a_relative_image_still_renders():
    """The other half of the flip: refusing CROSS-HOST images must not stop images working.

    Asserted per-attribute rather than as one serialized tag, so adding a safe attribute or
    reordering `src`/`alt` does not fail a test whose concern is only whether images render.
    """
    out = render._render_body("![alt text](./local.png)\n", style="design")
    tag = re.search(r"<img\b[^>]*>", out)
    assert tag, "no <img> emitted"
    assert 'src="./local.png"' in tag.group(0)
    assert 'alt="alt text"' in tag.group(0)
    assert "![alt text](./local.png)" not in out, "the markdown token must be consumed"


def test_a_link_is_still_a_link_beside_the_image_rule():
    """The `(?<!!)` guard added for the refusal path must not touch ordinary links."""
    out = render._render_body("[link](https://example.com) and text\n", style="design")
    assert '<a href="https://example.com">link</a>' in out


def test_horizontal_rule_renders(rich):
    assert "<hr" in rich
    assert "<p>---</p>" not in rich


def test_nested_bullet_nests(rich):
    assert re.search(r"<ul>.*<ul>", rich, re.S), "a nested bullet needs a nested <ul>"
    assert "  - nested child" not in rich


def test_doc_title_is_not_duplicated():
    """The seventh construct: the page header renders <h1>{title}</h1>, so a doc
    whose first line was `# <same title>` shipped TWO identical <h1>s."""
    out = render.render_artifact("# Doc Title\n\nBody.\n", title="Doc Title",
                                 style="design")
    assert out.count("<h1>Doc Title</h1>") == 1


def test_a_different_leading_h1_is_preserved():
    """Only an EXACT duplicate is dropped — a real first heading must survive."""
    out = render.render_artifact("# Different Heading\n\nBody.\n", title="Doc Title",
                                 style="design")
    assert "<h1>Different Heading</h1>" in out
    assert "<h1>Doc Title</h1>" in out, "the page header h1 must remain"


def test_plain_page_h1_behaviour_is_unchanged():
    """AC2 again: the dedupe is rich-only, so a plain page keeps what it emitted."""
    out = render.render_artifact("# Doc Title\n\nBody.\n", title="Doc Title",
                                 style="plain")
    assert out.count("<h1>Doc Title</h1>") == 2


# --- AC3: escape-first holds ------------------------------------------------------

HOSTILE = (
    "A [click](javascript:alert(1)) and [x](https://ok.example) plus "
    "![i](\"onerror=alert(1)) and <script>alert(1)</script> and *<b>em</b>*\n"
)


def test_rich_never_emits_an_unescaped_script(rich):
    out = render._render_body(HOSTILE, style="design")
    assert "<script>" not in out
    assert "&lt;script&gt;" in out


def test_rich_only_adds_whitelisted_tags():
    """Every `<` in the output must open a tag this renderer is allowed to emit."""
    out = render._render_body(PROBE + HOSTILE, style="design")
    allowed = {"p", "br", "h1", "h2", "h3", "h4", "h5", "h6", "ul", "ol", "li",
               "code", "strong", "em", "a", "img", "hr", "blockquote", "pre",
               "table", "thead", "tbody", "tr", "th", "td", "span", "section", "div"}
    for tag in re.findall(r"<\s*/?\s*([A-Za-z][A-Za-z0-9]*)", out):
        assert tag.lower() in allowed, f"unexpected tag <{tag}> in rich output"


def test_dangerous_url_schemes_are_not_linked():
    """A javascript: href is exactly the injection an <a> transform invites."""
    out = render._render_body(HOSTILE, style="design")
    assert 'href="javascript:' not in out.lower()
    assert 'src="javascript:' not in out.lower()


def test_image_attributes_cannot_break_out_of_the_quote():
    # The URL is RELATIVE on purpose (#23): with a cross-host URL the image is now refused,
    # so this test would pass because the construct went literal and would stop testing
    # quote-breakout at all — the same vacuity class #23 exists to remove.
    out = render._render_body('![a"onerror=alert(1)](./i.png)\n', style="design")
    assert "<img" in out, "the guard must still be exercised on an emitted attribute"
    assert "onerror=alert(1)" not in out or "&quot;onerror" in out
    assert "<script" not in out


def test_code_span_content_is_left_alone(rich_text="Use `*not italic*` and `[not](a link)`.\n"):
    out = render._render_body(rich_text, style="design")
    assert "<code>*not italic*</code>" in out
    assert "<code>[not](a link)</code>" in out


# --- Step 11 review findings, each reproduced then fixed ---------------------------

def test_emphasis_never_runs_inside_generated_markup():
    """Step 11 #1 (High): emphasis ran over HTML this renderer had just generated, so
    an asterisk in a URL became a TAG INSIDE AN href — a structural break of
    escape-first, not merely cosmetic."""
    out = render._render_body("[x](https://e/*p*)\n", style="design")
    assert '<a href="https://e/*p*">x</a>' in out
    assert "<em>" not in out, "emphasis must not touch a generated attribute"


def test_emphasis_does_not_misnest_across_a_strong_span():
    """Step 11 #1 (High), second case: `_a **b_ c**` produced
    `<em>a <strong>b</em> c</strong>` — overlapping, invalid nesting."""
    out = render._render_body("_a **b_ c**\n", style="design")
    assert "<strong>b_ c</strong>" in out
    assert "<em>" not in out


def test_nested_image_and_link_brackets_do_not_consume_each_other():
    """Step 11 #2 (Medium): the regexes were not bracket-aware."""
    out = render._render_body("![outer [inner](https://a)](https://b)\n", style="design")
    assert out.count("<img") == 0, "a malformed outer image must stay literal"
    assert '<a href="https://a">inner</a>' in out
    assert "<em>" not in out and "</a></a>" not in out


def test_nested_list_is_a_child_of_its_parent_item_not_a_sibling():
    """Step 11 #3 (Medium): `<ul><li>parent</li><ul>…</ul></ul>` is invalid — the
    nested list must live INSIDE the parent <li>."""
    out = render._render_body("- parent\n  - child\n- sibling\n", style="design")
    assert "<li>parent\n<ul>" in out, "the nested list must open inside the parent li"
    assert "</ul></li>" in out, "and close before the parent li closes"
    assert "</li>\n<ul>" not in out, "a nested list must never be a sibling of its item"
    assert out.count("<ul>") == out.count("</ul>")
    assert out.count("<li>") == out.count("</li>")


def test_intraword_underscore_stays_literal():
    """Step 11 #4 (Medium): `_foo_bar` became `<em>foo</em>bar`."""
    assert "<em>" not in render._render_body("_foo_bar\n", style="design")
    assert "<em>foo</em>" in render._render_body("_foo_ bar\n", style="design")


def test_intraword_asterisk_stays_literal():
    """The same guard, applied to `*` for symmetry."""
    assert "<em>" not in render._render_body("*foo*bar\n", style="design")


def test_ordered_list_preserves_its_start_number():
    """Step 11 #5 (Low): a list starting at 7 rendered as item 1."""
    out = render._render_body("7. seventh\n8. eighth\n", style="design")
    assert '<ol start="7">' in out
    assert '<ol>' in render._render_body("1. one\n2. two\n", style="design"), \
        "a list starting at 1 needs no start attribute"


def test_list_tags_stay_balanced_on_a_ragged_dedent():
    """A dedent to a level that never opened must not leak or over-close tags."""
    out = render._render_body("- a\n    - deep\n  - mid\n- back\n\npara\n", style="design")
    assert out.count("<ul>") == out.count("</ul>")
    assert out.count("<li>") == out.count("</li>")
    assert "<p>para</p>" in out


# --- #122: `_safe_url` refused ordinary relative paths ----------------------------------

RICH_STYLES = sorted(s for s in render._TEMPLATES if s != "plain")


class TestSafeUrlAcceptsOrdinaryRelativeReferences:
    """#122. The allowlist read `^(?:https?:|mailto:|#|/|\\./|\\.\\./)`, so "relative" meant
    only a path starting `/`, `./` or `../`. `assets/diagram.png` — the most ordinary markdown
    image path there is — matched nothing and rendered as literal source text, with no error and
    no warning."""

    @pytest.mark.parametrize("url", [
        "assets/diagram.png",
        "sub/dir/x.png",
        "diagram.png",
        "../up/one.png",          # already worked; pinned so widening cannot lose it
        "./here.png",
        "/rooted.png",
        "dir/a:b.png",            # a colon AFTER a path segment is not a scheme
    ])
    def test_a_bare_relative_image_renders(self, url):
        assert md._safe_url(url) == url, url

    @pytest.mark.parametrize("url", ["?v=2", "#section", "?a=1&amp;b=2"])
    def test_a_query_or_fragment_relative_reference_renders(self, url):
        """AC2."""
        assert md._safe_url(url) == url, url

    @pytest.mark.parametrize("style", RICH_STYLES)
    def test_a_bare_relative_image_renders_in_every_rich_style(self, style):
        """AC1 says 'in every style that uses the rich inline pass', so this walks them all
        rather than trusting one representative."""
        out = render._render_body("![d](assets/diagram.png)\n", style=style)
        assert 'src="assets/diagram.png"' in out, style
        assert "![d](assets/diagram.png)" not in out, f"{style} still rendered literal source"

    @pytest.mark.parametrize("style", RICH_STYLES)
    def test_a_bare_relative_link_renders_in_every_rich_style(self, style):
        out = render._render_body("[see the notes](notes.md)\n", style=style)
        assert 'href="notes.md"' in out, style

    def test_plain_stays_literal_because_it_has_no_rich_inline_pass(self):
        """`plain` is byte-pinned and never had the inline pass, so it is unaffected — the point
        is that this is unchanged behaviour, not a #122 regression."""
        out = render._render_body("![d](assets/diagram.png)\n", style="plain")
        assert "<img" not in out


class TestSafeUrlStillRefusesEverythingDangerous:
    """AC3. Widening an allowlist is where a security guard gets lost, so every form that was
    refused before must still be refused."""

    @pytest.mark.parametrize("url", [
        # dangerous schemes, and the mixed case a lowercase-only guard would miss
        "javascript:alert(1)", "JavaScript:alert(1)", "JAVASCRIPT:alert(1)",
        "data:text/html;base64,PHNjcmlwdD4=", "DaTa:text/html,x",
        "vbscript:msgbox", "VBScript:msgbox",
        "file:///etc/passwd",
        # a scheme-like token is a SCHEME, not a relative path — a browser agrees
        "foo:bar",
        # protocol-relative and the reverse-solidus forms #23 established resolve to a host
        "//evil.example/x", "/\\evil.example/x", "\\/evil.example/x", "\\\\evil.example/x",
    ])
    def test_a_dangerous_or_host_bearing_url_is_refused(self, url):
        assert md._safe_url(url) is None, url

    @pytest.mark.parametrize("url", ["https://ok.example/x", "http://ok.example/x",
                                     "HtTpS://ok.example/x", "mailto:a@b.example"])
    def test_the_three_allowed_schemes_still_pass(self, url):
        assert md._safe_url(url) == url, url

    def test_an_absolute_image_is_still_refused_by_the_separate_external_rule(self):
        """AC3's last clause: `_safe_url` allowlists the scheme and returns
        `https://h/i.png` happily; `_is_external` is a SECOND, independent rejection at the
        `_img` call site. Widening the first must not weaken the second."""
        out = render._render_body("![i](https://evil.example/i.png)\n", style="design")
        assert "<img" not in out
        assert 'href="https://ok.example"' in render._render_body(
            "[cite](https://ok.example)\n", style="design"), \
            "an <a> may still point off-host — a citation is not a request"

    @pytest.mark.parametrize("url", [
        # A C0 control or a TAB/CR/LF hides a `//host` prefix from a naive classifier while the
        # URL parser discards it and fetches. `_is_external` does NOT catch these on its own
        # (measured: `_is_external('\x01//evil.example/x')` is False), so if `_safe_url` admits
        # them the `_img` guard does not save the page — the widening must classify on the
        # URL Standard's normalised value.
        "\x01//evil.example/x",
        "\x00//evil.example/x",
        "\x1f//evil.example/x",
        "/\r/evil.example/x",
        "/\t/evil.example/x",
        "/\n/evil.example/x",
        "htt\tps://evil.example/x",
        "java\tscript:alert(1)",
    ])
    def test_a_control_character_cannot_smuggle_a_host_or_a_scheme(self, url):
        assert md._safe_url(url) is None, repr(url)

    @pytest.mark.parametrize("url", ["", "   ", "a b.png", "a<b.png", "a>b.png"])
    def test_empty_and_structurally_unusable_urls_are_refused(self, url):
        assert md._safe_url(url) is None, repr(url)

    @pytest.mark.parametrize("url", [
        # A character reference carries no scheme AS WRITTEN, but the browser decodes the
        # attribute value BEFORE parsing the url — so the string this guard judges is not the
        # one that resolves. The old prefix allowlist refused these by accident; widening to
        # "no scheme means relative" admitted them until both readings were classified.
        "javascript&colon;alert(1)",
        "&#x6a;avascript:alert(1)",
        "&#106;avascript:alert(1)",
        "&#47;&#47;evil.example/x",
        "&sol;&sol;evil.example/x",
        "&Tab;javascript:alert(1)",
    ])
    def test_a_character_reference_cannot_smuggle_a_scheme_past_the_guard(self, url):
        assert md._safe_url(url) is None, url

    def test_the_double_reading_does_not_refuse_a_legitimate_escaped_url(self):
        """`&amp;` is how an ordinary `&` arrives, so the decoded reading must stay allowed."""
        assert md._safe_url("?a=1&amp;b=2") == "?a=1&amp;b=2"
        assert md._safe_url("dir/file&amp;name.png") == "dir/file&amp;name.png"

    def test_percent_encoded_slashes_are_not_an_authority(self):
        """A browser does not decode `%2f` before authority parsing, so this stays a same-origin
        path and must NOT be refused — over-refusing here would break legitimate paths."""
        assert md._safe_url("%2f%2fevil.example/x") == "%2f%2fevil.example/x"

    def test_the_escape_first_invariant_that_makes_this_defence_in_depth(self):
        """Why the character-reference forms are not a reachable exploit: the author's `&` is
        escaped to `&amp;` before `_safe_url` ever sees it, so the browser's decoded reading
        still holds a literal `&colon;` and no scheme forms. Measured through the real renderer,
        because this invariant is the whole reason the guard's old accident was survivable."""
        out = render._render_body("[a](javascript&colon;alert(1))\n", style="design")
        assert "javascript:alert" not in out
        assert "&amp;colon;" in out, "the author's & must arrive escaped"


@pytest.mark.parametrize("url", [
    # Step 11 (Low): `re.I` without `re.ASCII` case-folds Unicode, so `[a-z]` also matched
    # U+212A KELVIN SIGN and U+017F LATIN SMALL LETTER LONG S. Such a path was read as carrying
    # an unblessed scheme and rendered literal — an over-refusal, so it failed closed, but the
    # grammar it claims to implement is ASCII-only.
    "K:x.png",
    "ſ:x.png",
])
def test_a_non_ascii_case_folding_character_is_not_a_scheme(url):
    assert md._safe_url(url) == url, repr(url)


def test_the_normalisation_contract_this_guard_depends_on():
    """Step 11 (Medium) asked for `_url_value`'s contract to be auditable from here, because
    `_safe_url`'s security now rests on a helper in another module.

    Reimplementing it locally was DECLINED — that would fork a definition this codebase
    deliberately keeps single, the same reason `_is_external` is imported rather than copied
    (#23). The real risk is cross-module drift, so the contract is pinned instead: if
    `lint._url_value` ever stops stripping leading C0 controls or removing TAB/LF/CR, this test
    fails right next to the guard that relies on it.
    """
    from render.lint import _url_value
    assert _url_value("\x01//host") == "//host", "leading C0 controls must be stripped"
    assert _url_value("//host\x01") == "//host", "trailing C0 controls must be stripped"
    assert _url_value(" //host ") == "//host", "leading/trailing spaces must be stripped"
    assert _url_value("/\t/\r\n/host") == "///host", "TAB/LF/CR must be removed ANYWHERE"
    assert _url_value("a\x1fb") == "a\x1fb", "an INTERIOR C0 control is not stripped"
    # and the consequence the guard actually cares about
    assert md._safe_url("\x01//evil.example/x") is None


def test_safe_url_docstring_states_the_accepted_set_and_claims_no_live_defect():
    """AC4."""
    doc = md._safe_url.__doc__
    assert "KNOWN DEFECT" not in doc, "the #122 block must go when #122 closes"
    for phrase in ("http:", "https:", "mailto:", "relative"):
        assert phrase in doc, phrase
