"""The deploy step gets forgotten — so warn about it, and publish nothing (#44).

The standing mandate is that a design doc is done when its `.md` and `.html` are committed AND
the page is live. Three things, and the third silently gets skipped because nothing looks.

**Owner decision 2026-08-02: option (d) of the four the issue lists** — a check that WARNS, with
no publishing path at all. Not (5), auto-publish confined to preview URLs.

The reason is a property of the plan, not a preference. Production deploys here cannot be gated:
Vercel Authentication is unavailable for production (`invalid_sso_protection`), team password
protection is off, and `protection enable --sso` exempts the `<name>.vercel.app` alias. So any
design that auto-publishes puts unreviewed HTML on a public, indexable URL with no possible gate.
A warning closes the same failure mode with none of that exposure, and it cannot invert
`publish_doc.py`'s deliberate lint-before-deploy ordering because it never deploys.

**What counts as evidence of a deploy, locally.** The convention this workspace already follows is
that a design doc links its live page from the companion markdown — `· [live](https://….vercel.app)`
is in epic #77's own body. So the check pairs each rendered `.html` with its `.md` and looks for a
`vercel.app` URL. Local, offline and fast, which a Stop hook has to be.

**It always exits 0.** A Stop hook that fails would block the session over an advisory. The
product is the message, never a veto.
"""
import pytest
import subprocess
import sys
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(SCRIPTS))

import deploy_check  # noqa: E402

RENDERED = ('<!doctype html><html><head><meta name="generator" content="design-doc-publish">'
            "</head><body><footer>Last updated: x · generated by design-doc-publish "
            "— self-contained, no external resources.</footer></body></html>")

# A page rendered before #24: no generator meta, only the old footer prose.
LEGACY_RENDERED = ("<!doctype html><html><body><footer>Last updated: x · generated by "
                   "hooks/render_artifact.py — self-contained, no external resources.</footer>"
                   "</body></html>")

# A hand-written page that merely DISCUSSES the old footer — this repo's own planning docs do.
# It must not be mistaken for engine output.
PROSE_ONLY = ("<!doctype html><html><body><p>The footer used to read "
              "generated by hooks/render_artifact.py, which is now false.</p></body></html>")

HANDWRITTEN = "<!doctype html><html><body><p>not from the renderer</p></body></html>"


def _doc(tmp_path, name, html=RENDERED, md=None):
    (tmp_path / f"{name}.html").write_text(html, encoding="utf-8")
    if md is not None:
        (tmp_path / f"{name}.md").write_text(md, encoding="utf-8")
    return tmp_path


class TestItFindsThePageNobodyDeployed:
    def test_a_rendered_page_with_no_live_link_warns(self, tmp_path):
        _doc(tmp_path, "plan", md="# Plan\n\nNo link here.\n")
        assert deploy_check.undeployed(tmp_path) == [tmp_path / "plan.html"]

    def test_a_rendered_page_whose_markdown_links_it_is_quiet(self, tmp_path):
        _doc(tmp_path, "plan", md="# Plan\n\n· [live](https://example-plan-118.vercel.app)\n")
        assert deploy_check.undeployed(tmp_path) == []

    def test_a_live_link_inside_the_html_also_counts(self, tmp_path):
        """Some pages carry their own canonical link and have no companion markdown."""
        html = RENDERED.replace("</body>", "<a href='https://x.vercel.app'>live</a></body>")
        _doc(tmp_path, "solo", html=html)
        assert deploy_check.undeployed(tmp_path) == []

    def test_a_rendered_page_with_no_markdown_at_all_still_warns(self, tmp_path):
        _doc(tmp_path, "orphan")
        assert deploy_check.undeployed(tmp_path) == [tmp_path / "orphan.html"]

    def test_it_reports_every_offender_not_just_the_first(self, tmp_path):
        _doc(tmp_path, "a")
        _doc(tmp_path, "b")
        assert len(deploy_check.undeployed(tmp_path)) == 2


class TestItLeavesEverythingElseAlone:
    def test_a_hand_written_html_is_not_its_business(self, tmp_path):
        """Only pages this engine rendered are in scope — the mandate is about design docs."""
        _doc(tmp_path, "vendored", html=HANDWRITTEN)
        assert deploy_check.undeployed(tmp_path) == []

    def test_a_markdown_file_alone_is_not_an_offence(self, tmp_path):
        (tmp_path / "notes.md").write_text("# Notes\n", encoding="utf-8")
        assert deploy_check.undeployed(tmp_path) == []

    def test_a_derived_build_artifact_is_skipped(self, tmp_path):
        """`index/index.html` is gitignored and rebuilt from `vercel project ls`; it is not a
        design doc and warning about it would be permanent noise."""
        d = tmp_path / "index"
        d.mkdir()
        (d / "index.html").write_text(RENDERED, encoding="utf-8")
        assert deploy_check.undeployed(tmp_path) == []

    def test_an_unreadable_file_is_skipped_not_fatal(self, tmp_path):
        (tmp_path / "bad.html").write_bytes(b"\xff\xfe\x00not utf8 at all")
        assert deploy_check.undeployed(tmp_path) == []


class TestItCanNeverPublishAnything:
    # AC1's negative case, proved by CONSTRUCTION rather than by behaviour: a module that cannot
    # reach the network or spawn a process cannot put a half-finished page on a public URL.
    #
    # Asserted over the AST, not over the raw source. A substring grep was tried first and failed
    # on this module's own docstring, which necessarily explains WHY there is no Vercel call — so
    # the grep was banning the explanation along with the thing. Imports are what actually confer
    # the capability, and they are what is checked.
    FORBIDDEN_IMPORTS = {"subprocess", "urllib", "requests", "socket", "http", "os",
                         "publish_doc", "shutil"}

    def _imported(self):
        import ast
        tree = ast.parse(Path(deploy_check.__file__).read_text(encoding="utf-8"))
        names = set()
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                names.update(a.name.split(".")[0] for a in node.names)
            elif isinstance(node, ast.ImportFrom) and node.module:
                names.add(node.module.split(".")[0])
        return names

    def test_it_cannot_reach_the_network_or_spawn_a_process(self):
        assert not (self._imported() & self.FORBIDDEN_IMPORTS), self._imported()

    def test_it_does_not_import_the_publisher(self):
        assert "publish_doc" not in self._imported()

    def test_the_guard_would_catch_a_module_that_did(self):
        """The negative test's own negative test — an absence assertion that cannot fail is the
        defect this whole epic is about."""
        import ast
        tree = ast.parse("import subprocess\nx = 1\n")
        names = {a.name.split(".")[0] for n in ast.walk(tree)
                 if isinstance(n, ast.Import) for a in n.names}
        assert names & self.FORBIDDEN_IMPORTS


class TestItIsAdvisoryNeverAVeto:
    def test_the_cli_exits_zero_even_with_offenders(self, tmp_path):
        _doc(tmp_path, "plan")
        proc = subprocess.run([sys.executable, str(SCRIPTS / "deploy_check.py"), str(tmp_path)],
                              capture_output=True, text=True)
        assert proc.returncode == 0, "a Stop hook that fails would block the session"
        assert "plan.html" in proc.stdout + proc.stderr

    def test_the_cli_is_silent_when_there_is_nothing_to_say(self, tmp_path):
        _doc(tmp_path, "plan", md="[live](https://x.vercel.app)")
        proc = subprocess.run([sys.executable, str(SCRIPTS / "deploy_check.py"), str(tmp_path)],
                              capture_output=True, text=True)
        assert proc.returncode == 0
        assert (proc.stdout + proc.stderr).strip() == "", "silence is the normal case"

    def test_a_missing_path_is_not_an_error(self, tmp_path):
        proc = subprocess.run([sys.executable, str(SCRIPTS / "deploy_check.py"),
                               str(tmp_path / "nope")], capture_output=True, text=True)
        assert proc.returncode == 0


class TestHowAPageIsRecognisedAsEngineOutput:
    """#24 moved recognition from display prose to a structural marker.

    The old constant matched the footer text anywhere in the document, which coupled machine
    recognition to human-visible copy: renaming the footer silently stopped the check, and a
    page that merely quoted the phrase was treated as engine output.
    """

    def test_the_generator_meta_is_recognised(self, tmp_path):
        _doc(tmp_path, "plan", html=RENDERED)
        assert deploy_check.undeployed(tmp_path) == [tmp_path / "plan.html"]

    def test_a_pre_24_page_is_still_recognised_by_its_footer(self, tmp_path):
        """Five pages were already committed without the meta. Dropping legacy support would
        silently stop checking them, which is the failure this arm exists to prevent."""
        _doc(tmp_path, "plan", html=LEGACY_RENDERED)
        assert deploy_check.undeployed(tmp_path) == [tmp_path / "plan.html"]

    def test_prose_quoting_the_old_footer_is_not_engine_output(self, tmp_path):
        """The legacy arm requires the mark inside a <footer>, so this repo's own planning docs
        — which quote the phrase while describing the bug — are not misclassified."""
        _doc(tmp_path, "plan", html=PROSE_ONLY)
        assert deploy_check.undeployed(tmp_path) == []

    def test_a_handwritten_page_is_still_out_of_scope(self, tmp_path):
        _doc(tmp_path, "plan", html=HANDWRITTEN)
        assert deploy_check.undeployed(tmp_path) == []

    # Structural boundary cases. Substring matching got every one of these wrong in at least one
    # direction, and both directions are silent: a false positive is a spurious warning, a false
    # negative is a page that stops being checked at all.
    _MARK = "generated by hooks/render_artifact.py"
    _META = '<meta name="generator" content="design-doc-publish">'

    @pytest.mark.parametrize("label,html,expected", [
        ("empty",                  "", False),
        ("nothing to find",        "<html><body>x</body></html>", False),
        ("meta in head",           f"<html><head>{_META}</head><body>x</body></html>", True),
        ("meta, attrs reordered",  "<html><head><meta content='design-doc-publish' "
                                   "name='generator'></head></html>", True),
        ("meta, attr name cased",  '<html><head><meta NAME="Generator" '
                                   'content="design-doc-publish"></head></html>', True),
        ("meta in body, not head", f"<html><body>{_META}</body></html>", False),
        ("meta inside pre",        f"<html><head><pre>{_META}</pre></head></html>", False),
        ("legacy bare footer",     f"<html><footer>{_MARK}</footer></html>", True),
        ("legacy footer w/ attrs", f'<html><footer class="x">{_MARK}</footer></html>', True),
        ("legacy FOOTER uppercase", f"<html><FOOTER>{_MARK}</FOOTER></html>", True),
        ("legacy unclosed footer", f"<html><footer>{_MARK}", True),
        ("second footer carries it", f"<html><footer>x</footer><footer>{_MARK}</footer></html>", True),
        ("prose only",             f"<html><body><p>{_MARK}</p></body></html>", False),
        ("bare comment",           f"<html><!-- {_MARK} --></html>", False),
        ("commented-out footer",   f"<html><!-- <footer>{_MARK}</footer> --></html>", False),
        ("example inside a footer", f"<html><footer><pre>{_MARK}</pre></footer></html>", False),
        ("code inside a footer",   f"<html><footer><code>{_MARK}</code></footer></html>", False),
        ("text after </footer>",   f"<html><footer>x</footer>{_MARK}</html>", False),
        ("unparseable garbage",    "<<<>>>&&&<footer", False),
    ])
    def test_recognition_is_structural_not_substring(self, label, html, expected):
        assert deploy_check._is_rendered(html) is expected, label

    def test_no_input_shape_can_raise(self):
        """This runs in a Stop hook; a checker that raises is a checker that gets uninstalled."""
        for html in ("", "<", "<footer", "<!--", "&#xZZ;", "\x00\x01", "<html>" * 5000):
            assert deploy_check._is_rendered(html) in (True, False)

    def test_the_real_renderer_output_is_recognised(self, tmp_path):
        """Pins the consumer against the ACTUAL renderer rather than a hand-typed fixture, so a
        future footer or meta change cannot pass by updating only the test's copy of the string."""
        sys.path.insert(0, str(SCRIPTS))
        import render  # noqa: PLC0415
        html = render.render_artifact("# T\n\nbody\n", title="T", generated_at="2026-08-03 00:00 MDT")
        (tmp_path / "real.html").write_text(html, encoding="utf-8")
        assert deploy_check.undeployed(tmp_path) == [tmp_path / "real.html"]
