#!/usr/bin/env python3
"""Warn when a rendered page was committed and nothing records a deploy (#44).

The standing mandate is that a design doc is done when its `.md` and `.html` are committed AND
the page is live. Three things, and the third is the one that silently gets skipped, because
nothing looks for it.

**This warns. It has no publishing path, and that is the whole design** (owner decision
2026-08-02, option (d) of the four the issue weighs). Anything that publishes automatically
puts unreviewed HTML on a live URL with no gate, and a write-triggered hook would additionally
invert the lint-before-publish ordering `publish_doc.py` deliberately has.

A warning closes the same failure mode with none of that exposure, and it cannot invert an
ordering it never participates in.

**What counts as evidence of a live page, offline.** The convention this workspace already
follows is that a design doc links its live page from the companion markdown —
`· [live](https://<name>.3dstories.ca)`. So each rendered `.html` is paired with its same-stem
`.md` and searched for a zone URL; a link inside the HTML itself counts too, for a page that has
no companion. This is a heuristic over a CONVENTION, not a query against the harness: a Stop
hook has to be local, offline and fast, and it must not need a credential.

**Consequences of that choice, stated rather than discovered later.** A page deployed but never
linked is reported as undeployed — a false alarm, and the fix is to link it, which the mandate
wants anyway. A page linked but whose deployment has since been deleted is reported as fine — a
false silence this cannot see without the network. Neither can put anything on the internet.

Usage: `deploy_check.py [root ...]` — prints one line per offender, ALWAYS exits 0.

INSTALLING IT AS A STOP HOOK. The hook config lives in `~/.claude/settings.json`, outside this
repo, so nothing here can install it:

    {"hooks": {"Stop": [{"matcher": "", "hooks": [{"type": "command",
      "command": "python3 <repo>/scripts/deploy_check.py <repo>/docs"}]}]}}

Running it by hand before a PR works just as well and needs no configuration.

**These instructions live HERE and not in `SKILL.md` on purpose.** #19 cut that file from 205
lines to 50 and pins the budget with three tests — 50 lines, exactly ONE runnable block, and no
step a reader has to assemble by hand. #44's first attempt added a section there and broke all
three at once; worse, the gate had been run BEFORE that edit, so `main` went red behind a PR body
claiming it was green. The budget is the deliverable, and a usage note is not worth spending it.
"""
from __future__ import annotations

import sys
from html.parser import HTMLParser
from pathlib import Path

# How a page is recognised as this engine's output — which is what keeps hand-written and
# vendored HTML out of scope: the mandate is about docs this engine produced.
#
# #24: the marker is now STRUCTURAL, not display copy. Matching human-visible footer prose
# coupled machine recognition to wording: any hand-written page that merely *discussed* the
# phrase was classified as engine output, and every rename of the footer silently broke the
# check until someone remembered to edit this constant too.
_GENERATOR_ID = "design-doc-publish"
_GENERATOR_MARK = f'<meta name="generator" content="{_GENERATOR_ID}">'

# Pages rendered before #24 carry no generator meta, only the old footer stamp. Retained so the
# already-committed pages keep being checked rather than silently skipped.
# RETIREMENT: drop this arm once no committed page still carries the legacy stamp —
#   git grep -l 'generated by hooks/render_artifact.py' -- '*.html'
# returning nothing is the condition. (It is deliberately phrased on the LEGACY stamp's absence,
# not on the new marker's presence: most tracked HTML here is hand-written or vendored and will
# never carry the generator meta, so a presence-based condition could never be met.)
_LEGACY_RENDERED_MARK = "generated by hooks/render_artifact.py"

# Never treated as provenance, wherever they appear: an example of the marker is not the marker.
_OPAQUE = {"pre", "code", "script", "style", "textarea"}


class _ProvenanceScanner(HTMLParser):
    """Finds engine provenance STRUCTURALLY — as markup, not as a substring.

    Substring matching was the original sin here: it could not tell a `<footer>` element from
    the same characters inside a comment, a code sample or ordinary prose, and it missed a
    footer that carried an attribute or a capital letter. Both directions are silent, and this
    checker's whole job is deciding what to look at.

    Comments need no handling: HTMLParser does not emit tag or data events for their contents,
    so a commented-out footer is invisible here, which is correct.
    """

    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.found = False
        self._head = 0
        self._footer = 0
        self._opaque = 0

    def handle_starttag(self, tag, attrs):
        if tag == "head":
            self._head += 1
        elif tag == "footer":
            self._footer += 1
        elif tag in _OPAQUE:
            self._opaque += 1
        elif tag == "meta" and self._head and not self._opaque:
            a = {(k or "").lower(): (v or "") for k, v in attrs}
            if a.get("name", "").strip().lower() == "generator" \
                    and a.get("content", "").strip() == _GENERATOR_ID:
                self.found = True

    def handle_endtag(self, tag):
        if tag == "head" and self._head:
            self._head -= 1
        elif tag == "footer" and self._footer:
            self._footer -= 1
        elif tag in _OPAQUE and self._opaque:
            self._opaque -= 1

    def handle_data(self, data):
        if self._footer and not self._opaque and _LEGACY_RENDERED_MARK in data:
            self.found = True


def _is_rendered(html: str) -> bool:
    """True when this engine produced the page.

    Recognised two ways: a `<meta name="generator">` element in `<head>` naming this engine, or
    — for pages rendered before #24 — the legacy stamp in a `<footer>` element's own text. Both
    are checked as MARKUP, so a page that merely quotes either one in prose, a comment or a code
    sample is not mistaken for engine output. This repo's own planning docs do exactly that.

    Never raises. It runs in a Stop hook, and a checker that raises is a checker that gets
    uninstalled — so a document too malformed to parse is reported as "not ours" rather than
    taking the session down with it.
    """
    scanner = _ProvenanceScanner()
    try:
        scanner.feed(html)
        scanner.close()
    except Exception:
        return False
    return scanner.found

_LIVE_MARK = "3dstories.ca"

# Derived build artifacts, not design docs. The index is server-rendered by the harness;
# warning about a build artifact forever would train the reader to ignore the warning.
_SKIP_PARTS = {"index", "node_modules", ".git"}


def _text(path: Path) -> str:
    """File contents, or empty when it cannot be read as text. A checker that raises on one
    stray byte is a checker that gets uninstalled."""
    try:
        return path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return ""


def _has_live_link(page: Path, html: str) -> bool:
    if _LIVE_MARK in html:
        return True
    return _LIVE_MARK in _text(page.with_suffix(".md"))


def undeployed(root: Path) -> list[Path]:
    """Rendered pages under `root` with nothing recording a deploy, sorted for a stable report."""
    root = Path(root)
    if not root.exists():
        return []
    out = []
    for page in sorted(root.rglob("*.html")):
        if _SKIP_PARTS & set(page.parts):
            continue
        html = _text(page)
        if not _is_rendered(html):
            continue
        if not _has_live_link(page, html):
            out.append(page)
    return out


def main(argv: list[str]) -> int:
    roots = [Path(a) for a in argv[1:]] or [Path.cwd()]
    offenders = [p for r in roots for p in undeployed(r)]
    if offenders:
        print("design-doc-publish: rendered and committed, but nothing records a deploy —")
        for p in offenders:
            print(f"  {p}")
        print("  Publish with `publish_doc.py`, then link the live URL from the companion .md.")
    # ALWAYS 0. This is advisory; a Stop hook that fails blocks the session over a nudge.
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
